SET TERM !! ;
SET SQL DIALECT 3!!
SET NAMES UTF8!!

CREATE DATABASE '/db/mvc.fdb'
USER 'SYSDBA' PASSWORD '0'
PAGE_SIZE 8192
DEFAULT CHARACTER SET UTF8!!

CREATE TABLE PERSONAS (
    ID       INTEGER NOT NULL,
    NOMBRE     VARCHAR(100),
    EDAD  VARCHAR(10),
    SEXO VARCHAR(1),
    CASADO INTEGER,
    CONSTRAINT PERSONAS_PK PRIMARY KEY (ID)
)!!

CREATE GENERATOR GEN_PERSONAS!!
SET GENERATOR GEN_PERSONAS TO 0!!

CREATE TRIGGER PERSONAS_BEFINS FOR PERSONAS ACTIVE
BEFORE insert POSITION 0
AS
BEGIN
  IF (NEW.ID is null) THEN
    NEW.ID = GEN_ID(GEN_PERSONAS,1);
END!!

INSERT INTO PERSONAS (NOMBRE, EDAD, SEXO, CASADO) VALUES ('Daniel', '36', 'M', 1)!!
INSERT INTO PERSONAS (NOMBRE, EDAD, SEXO, CASADO) VALUES ('Hugo', '8', 'M', 0)!!
INSERT INTO PERSONAS (NOMBRE, EDAD, SEXO, CASADO) VALUES ('Paco', '9', 'M', 0)!!
INSERT INTO PERSONAS (NOMBRE, EDAD, SEXO, CASADO) VALUES ('Luis', '10', 'M', 0)!!

SET TERM ; !!
